config/routes.rb
Rails.application.routes.draw do
  root 'home#top'
  get 'home/about'
  devise_for :users
  resources :users,only: [:show,:index,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#follower', as: 'follows'
    get 'followers' => 'relationships#followed', as: 'followers'
  end
  resources :books,except: [:new] do
    # bookに対してcomments, favoriteの関係なので書き分ける
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}

	belongs_to :user

  has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
	belongs_to :user
	belongs_to :book

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  # 参照したいクラス名、実際のクラス名
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,:validatable

  attachment :profile_image, destroy: false

  has_many :books, dependent: :destroy #userモデルの消去=>booksの消去
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :name, presence: true
  validates :introduction, length: {maximum: 50}

  # フォロー取得。カラムごとにアソシエーションを行なっている？
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー取得
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人

  def follow(user_id)
    follower.create(followed_id: user_id)
  end
  
  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end
  
  # フォローしていればtrueを返す
  def following?(user)
    following_user.include?(user)
  end
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
	before_action :configure_permitted_parameters, if: :devise_controller?
	#デバイス機能実行前にconfigure_permitted_parametersの実行をする。
	protect_from_forgery with: :exception

  protected
  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  #sign_out後のredirect先変更する。rootパスへ。rootパスはhome topを設定済み。
  def after_sign_out_path_for(resource)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    #sign_upの際にnameのデータ操作を許。追加したカラム。
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
	before_action :ensure, only: [:destroy]

	def create
		@book = Book.find(params[:book_id])
		@book_comment = BookComment.new(book_comment_params)
		@book_comment.user_id = current_user.id
		@book_comment.book_id = @book.id
		if @book_comment.save
      redirect_to book_path(@book), notice: "successfully created comment!"
    else
      @user = User.find(@book.user_id)
      @post_book = Book.new
      render  'books/show'
    end
  end
  def destroy
    book = Book.find(params[:book_id])
    comment = BookComment.find(params[:id])
    comment.destroy
    redirect_to book_path(book), notice: "successfully delete comment!"
  end

  private
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
  def ensure
    if current_user.id != BookComment.find(params[:id]).user_id
     redirect_to root_path
   end
 end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :ensure, {only: [:edit, :update]}

  def show
  	@book = Book.find(params[:id])
    @user = User.find(@book.user_id)
    @post_book = Book.new
    @book_comment = BookComment.new
  end
  def index
  	@books = Book.all
    @book = Book.new
  end
  def create
  	@book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "successfully created book!"
    else
      @books = Book.all
      render 'index'
    end
  end
  def edit
  	@book = Book.find(params[:id])
  end
  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
  		redirect_to @book, notice: "successfully updated book!"
  	else
  		render "edit"
  	end
  end
  def delete
  	@book = Book.find(params[:id])
  	@book.destoy
  	redirect_to books_path, notice: "successfully delete book!"
  end

  def ensure
    if current_user.id != Book.find(params[:id]).user_id
      redirect_to books_path
    end
  end

  private

  def book_params
  	params.require(:book).permit(:title, :body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_back(fallback_location: books_path)
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_back(fallback_location: books_path)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!

  def top
  end

  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end

  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end

  def follower
    @user = User.find(params[:user_id])
    @users = @user.following_user
  end

  def followed
    @user = User.find(params[:user_id])
    @users = @user.follower_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :baria_user, only: [:update, :edit]

  def show
  	@user = User.find(params[:id])
  	@books = @user.books
  	@book = Book.new
  end

  def index
  	@users = User.all #一覧表示するためにUserモデルのデータを全て変数に入れて取り出す。
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  		redirect_to user_path(@user.id), notice: "successfully updated user!"
  	else
      @book = Book.new
  		render :edit
  	end
  end

  private
  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image)
  end

  #url直接防止　メソッドを自己定義してbefore_actionで発動。
   def baria_user
  	unless params[:id].to_i == current_user.id
  		redirect_to user_path(current_user)
  	end
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_newform.html.erb
<%= form_for(book) do |f| %>
	<div class="field row">
		<%= f.label :title %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<%= f.label :body %> <!-- ここを変更 -->
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>

	<div class="actions row">
		<%= f.submit class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>

app/views/books/edit.html.erb
<div class="row">
<div class="col-md-6 col-md-offset-3">

<h1>Editing Book</h1>
<% if @book.errors.any? %>
<div id="error_explanation">
	<h2><%= @book.errors.count %> errors prohibited this object from being saved:</h2>

	<ul>
		<% @book.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
	</ul>
</div>
<% end %>
<%= render "books/newform", book: @book %>
<%= link_to "Show", @book, class: "book_#{@book.id}" %>
<%= link_to "Back", books_path, class: "back" %>

</div>
<div class="col-md-3"></div>

</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
<div id="error_explanation">
	<h2><%= @book.errors.count %> errors prohibited this object from being saved:</h2>

	<ul>
		<% @book.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
	</ul>
</div>
<% end %>
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>

	</div>

	<div class="col-xs-9">
		<h2>Books index</h2>
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="2"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to(book.user) do %>
						<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %><br>
						<%= book.user.name %>
						<% end %>
					</td>
					<td><%= link_to book.title, book, class: "book_#{book.id}" %></td>
					<td><%= book.body %></td>
					<td>
						<% if book.favorited_by?(current_user) %>
						<%= link_to book_favorites_path(book), method: :delete do %>
							<span class="glyphicon glyphicon-heart"></span>
							<%= book.favorites.count %>
						<% end %>
						<% else %>
						<%= link_to book_favorites_path(book), method: :post do %>
							<span class="glyphicon glyphicon-heart-empty"></span>
							<%= book.favorites.count %>
						<% end %>
						<% end %>
					</td>
					<td>
						コメント数: <%= book.book_comments.count %>
					</td>
				</tr>
				<% end %>
			</tbody>
		</table>



	</div>
</div>

app/views/books/show.html.erb
<% if @book_comment.errors.any? %>
<div id="error_explanation">
	<h2><%= @book_comment.errors.count %> errors prohibited this object from being saved:</h2>

	<ul>
		<% @book_comment.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
	</ul>
</div>
<% end %>
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: @user %>

		<h2>New book</h2>
		<%= render 'books/newform', book: @post_book %>

	</div>

	<div class="col-xs-9">
		<h2>Book detail</h2>

		<table class="table">
			<tr>
				<td>
					<%= link_to (@book.user) do %>
					<%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><br>
					<%= @book.user.name %>
					<% end %>
				</td>
				<td><%= link_to @book.title, @book %></td>
				<td><%= @book.body %></td>
				<td>
					<% if @book.favorited_by?(current_user) %>
					<%= link_to book_favorites_path(@book), method: :delete do %>
					<span class="glyphicon glyphicon-heart"></span>
					<%= @book.favorites.count %>
					<% end %>
					<% else %>
					<%= link_to book_favorites_path(@book), method: :post do %>
					<span class="glyphicon glyphicon-heart-empty"></span>
					<%= @book.favorites.count %>
					<% end %>
					<% end %>
				</td>
				<td>コメント数: <%= @book.book_comments.count %>
					<% if @book.user_id == current_user.id %>
					<td><%= link_to "Edit",edit_book_path(@book), class: "btn-sm btn-success edit_book_#{@book.id}" %></td>
					<td><%= link_to "Destroy",@book, method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %></td>
					<% end %>
				</tr>
			</table>

			<h2>Comments</h2>

			<% @book.book_comments.each do |f| %>
			<table class="table">
				<tr>
					<td>
						<%= link_to(f.user) do %>
						<%= attachment_image_tag(f.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %><br>
						<%= f.user.name %>
						<% end %>
					</td>
					<td><%= f.comment %></td>
					<% if f.user_id == current_user.id %>
					<td><%= link_to "Destroy", book_book_comment_path(@book, f), method: :delete, class: "btn-sm btn-danger" %></td>
					<% end %>
				</tr>
				<% end %>
			</table>

			<%= form_for [@book, @book_comment] do |f| %>
			<%= f.text_area :comment, size: "70*50"  %>
			<%= f.submit "送信" %>
			<% end %>

		</div>
	</div>

app/views/home/about.html.erb
<h1>welcome to<span class="glyphicon glyphicon-book"></span>
<strong>Bookers</strong>  !!</h1>

app/views/home/top.html.erb
<div class="row">
	<div class="main col-md-offset-3 col-md-6">
		<h1>welcome to<span class="glyphicon glyphicon-book"></span>
			<strong>Bookers</strong>  !!</h1>
			<p>In <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>,</p>
			<p>you can share and exchange your opinions , inpressions , and emotions</p>
			<p>about varioius books!</p>

			<div class="btn-wrapper">
				<div class="row">
					<p><%=link_to "Log in", new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1" %></p>
				</div>
				<div class="row">
					<p><%=link_to "Sign up", new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1" %></p>
				</div>
			</div>

	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--ヘッダーの記述-->
    <<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">

        <nav class="nav navbar-nav navbar-left">
          <span>Bookers</span>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <!--if文でサインインとアウト時の表示を変更-->
            <% if user_signed_in? %>
            <li><%= link_to ' home', user_path(current_user), class: 'glyphicon glyphicon-home home' %></li>
            <li><%= link_to ' users', users_path, class: 'glyphicon glyphicon-user users' %></li>
            <li><%= link_to ' books', books_path, class: 'glyphicon glyphicon-book books' %></li>
            <li><%= link_to ' logout', destroy_user_session_path, method: :delete, class: 'glyphicon glyphicon-log-out logout' %></li>
            <% else %>
            <li><%= link_to ' home', root_path, class: 'glyphicon glyphicon-home home' %></li>
            <li><%= link_to ' about', home_about_path, class: 'glyphicon glyphicon-link about' %></li>
            <li><%= link_to ' sign up', new_user_registration_path, class: 'glyphicon glyphicon-edit sign_up' %></li>
            <li><%= link_to ' login', new_user_session_path, class: 'glyphicon glyphicon-log-in sign_in' %></li>
            <% end %>
          </ul>
        </nav>

      </div>
    </header>
    <!--ヘッダーの記述-->
    <div class="container">
      <p id="notice"><%= notice %></p> <!--デバイスでnotice設定されているので呼び出してるだけ-->

      <%= yield %>

    </div>
  </body>
</html>

app/views/relationships/followed.html.erb
<h2><%= @user.name %>'s Follower</h2>
<% if @users.count > 0 %>
  <%= render 'users/index', users: @users %>
<% else %>
<p>ユーザーはいません</p>
<% end %>

app/views/relationships/follower.html.erb
<h2><%= @user.name %>'s Follow</h2>
<% if @users.count > 0 %>
  <%= render 'users/index', users: @users %>
<% else %>
<p>ユーザーはいません</p>
<% end %>

app/views/users/_index.html.erb
<table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th>follows</th>
      <th>followers</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
      <td><%= user.name%></td>
      <td><%= link_to user.follower.count, user_follows_path(user) %></td>
      <td><%= link_to user.followed.count, user_followers_path(user) %></td>

      <% if user != current_user %>
        <td>
        <% if current_user.following?(user) %>
          <%= link_to "Unfollow", user_relationships_path(user), method: :delete %>
        <% else %>
          <%= link_to "Follow", user_relationships_path(user), method: :post %>
        <% end %>
        </td>
      <% else %>
        <td></td>
      <% end %>

      <td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_profile.html.erb
<table class="table">
	<tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>

	<tr>
		<th>name</th>
		<th><%= user.name %></th>
	</tr>

	<tr>
		<th>introduction</th>
		<th><%= user.introduction %></th>
	</tr>
	<tr>
		<th>Comments</th>
		<th><%= user.book_comments.count %></th>
	</tr>
	<tr>
		<th>follows</th>
		<th><%= link_to user.follower.count, user_follows_path(user) %></th>
	</tr>
	<tr>
		<th>followers</th>
		<th><%= link_to user.followed.count, user_followers_path(user) %></th>
	</tr>
</table>

<div class="row">
	<% if user == current_user %>
		<%= link_to '',edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
	<% else %>
		<div class="col-xs-12">
			<% if current_user.following?(user) %>
			<%= link_to "Unfollow", user_relationships_path(user), method: :delete, class: "btn btn-primary" %>
			<% else %>
			<%= link_to "Follow", user_relationships_path(user), method: :post, class: "btn btn-success" %>
			<% end %>
		</div>
	<% end %>
</div>

app/views/users/edit.html.erb
<h2>User info</h2>

<%= form_for(@user) do |f| %>

<% if @user.errors.any? %>
	<h3><%= @user.errors.count %>error occurrence</h3>
	<ul>
		<% @user.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
<% end %>

<div class="field">
	<%= f.label :name %>
	<%= f.text_field :name, class: "name" %>
</div>

<div class="field">
	<%= f.label :image %>
	<%= f.attachment_field :profile_image, class: "user_image" %>
</div>

<div class="field">
	<%= f.label :introduction %>
	<%= f.text_area :introduction, class: "introduction" %>
</div>

<div class="actions">
	<%= f.submit %>
</div>

<% end %>

app/views/users/index.html.erb
<div class="row">
<div class="col-xs-3">
<h2>User info</h2>
<%= render 'users/profile', user: current_user %>
<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

<h2>New book</h2>
<%= render 'books/newform', book: @book %>
</div>

<div class="col-xs-9">
<h2>Users</h2>
	<%= render 'index', users: @users %>
</div>
</div>

app/views/users/show.html.erb
<div class="row">
	<div class="col-xs-3">
		<h2>User info</h2>
		<%= render 'users/profile', user: @user %>
		<!--同コントローラーのviewで表示ならusersは省略可 -->

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>
	</div>

	<div class="col-xs-9">
		<h2>Books</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to (book.user) do %>
						<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
						<% end %>
					</td>
					<td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
					<td><%= book.body %></td>
					<td>
						<% if book.favorited_by?(current_user) %>
						<%= link_to book_favorites_path(book), method: :delete do %>
						<span class="glyphicon glyphicon-heart"></span>
						<%= book.favorites.count %>
						<% end %>
						<% else %>
						<%= link_to book_favorites_path(book), method: :post do %>
						<span class="glyphicon glyphicon-heart-empty"></span>
						<%= book.favorites.count %>
						<% end %>
						<% end %>
					</td>
					<td>
						コメント数: <%= book.book_comments.count %>
					</td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>